### ISSUE TITLE
addClass, hasClass, and removeClass will have issues with input containing whitespace characters

### ISSUE THREAD

**Issue by zzzzBov** [AmpersandJS/amp#52] opened 2015-01-08 19:20 UTC
<sub>I'm including these three distinct issues in a single ticket as I believe that they should be resolved consistently.</sub>

[addClass][1], [hasClass][2], and [removeClass][3] will have inconsistent behavior between browsers when called with a class name such as `'foo bar'`.

## addClass

`addClass(el, 'foo bar')`

if the classList API is supported, a DOMException will be thrown
if the classList API is not supported `'foo bar'` will be added in a way that can cause class duplication.

## hasClass

`hasClass(el, 'foo bar')`

if the element happens to have those classes in that order, it will return `true`.

## removeClass

`removeClass(el, 'foo bar')`

if the classList API is supported, a DOMException will be thrown
if the classList API is not supported, `'foo bar'` will be removed only if those classes appear in that order.

# Recommendation

The API doesn't specify what should happen for trying to add multiple classes in a string. I believe that this should be fixed in a way to support utility to authors, even though it will cause a slight loss in performance and increase in code size.

I believe that it is obvious that `addClass(el, 'foo bar')` should be equivalent to `addClass(el, 'foo', 'bar')`, and that `removeClass(el, 'foo bar')` is equivalent to `removeClass(el, 'foo', 'bar')`.

I would also argue that `hasClass(el, 'foo bar')` should be treated as equivalent to `hasClass(el, 'foo') && hasClass(el, 'bar')`, however I am understanding of arguments for treating it as `hasClass(el, 'foo') || hasClass(el, 'bar')`, or explicitly disallowing that behavior to avoid possible author confusion.

That said, I am in favor of `hasClass(el, 'foo bar')` and the introduction of `hasClass(el, 'foo', 'bar')`, and `hasClass(el, ['foo', 'bar'])` as a means of specifying that an element has *all* of the listed classes.

[1]: https://github.com/AmpersandJS/amp/blob/master/modules/add-class/add-class.js
[2]: https://github.com/AmpersandJS/amp/blob/master/modules/has-class/has-class.js
[3]: https://github.com/AmpersandJS/amp/blob/master/modules/remove-class/remove-class.js

**Comment by HenrikJoreteg** [comment] 2015-01-09 04:17
Hi @zzzzBov thanks for submitting this. I'm not entirely convinced we should support whitespace separated class names when we already support doing this in two other ways. `addClass(el, 'one', 'two')` and `addClass(el, ['one', 'two']);` I'm not overly excited about introducing a third.

Also, the first `hasClass` implementation supported multiple arguments, but it was brought up that it wasn't entirely clear whether it meant "it has all these classes" or "it has any of these classes".

**Comment by zzzzBov** [comment] 2015-01-09 14:36
> I'm not entirely convinced we should support whitespace separated class names when we already support doing this in two other ways.

Then spaces should be explicitly disallowed in code and in the documentation.

Following the [principle of least astonishment][1] it would be better to allow spaces, and handle it gracefully than to throw an error that the user would then have to work around for a case that's trivial to handle.

> it wasn't entirely clear whether [`hasClass(el, 'foo', 'bar')`] meant "it has all these classes" or "it has any of these classes".

I have a C# implementation of `hasClass` that *can* handle multiple parameters, but I've **never** seen it used, so throwing an error with something like

    if (/[\r\n\f\t ]/.test(cls)) {
        throw new Error('Classes may not contain spaces');
    }

seems like an appropriate solution, and would be better than the current behavior that gives the false appearance of working.

[1]: http://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by wraithgar** [comment] 2015-01-09 16:50
:+1: on an explicit error in cases where the results would otherwise have been unexpected.

Any reason not to use `/\s/`?

**Comment by zzzzBov** [comment] 2015-01-09 19:08
@wraithgar,

as per the HTML5 spec, [classes are a list of space separated tokens][1], and the [space characters are defined as][2]:

* `\r`
* `\n`
* `\f`
* `\t`
* ` ` (space)

In JS, `\s` is equivalent to `[ \f\n\r\t\v​\u00a0\u1680​\u180e\u2000​\u2001\u2002​\u2003\u2004​\u2005\u2006​\u2007\u2008​\u2009\u200a​\u2028\u2029​​\u202f\u205f​\u3000]`, so `\s` is **not** an appropriate substitution.

[1]: http://www.w3.org/TR/html51/dom.html#classes
[2]: http://www.w3.org/TR/html51/infrastructure.html#space-character

**Comment by jdalton** [comment] 2015-01-09 19:50
Must go deeper. The spec also has a [skip whitepace](http://www.w3.org/TR/html51/infrastructure.html#skip-whitespace) in step 4 of [space-separated-tokens](http://www.w3.org/TR/html51/infrastructure.html#set-of-space-separated-tokens) which includes all those gnarly other whitespaces.

**Comment by zzzzBov** [comment] 2015-01-09 20:21
@jdalton 

Please re-read that section. #4 on "A set of space-separated tokens" says to "skip whitespace".

http://www.w3.org/TR/html51/infrastructure.html#skip-whitespace
> The step **skip whitespace** means that the user agent must collect a sequence of characters that are [space characters](http://www.w3.org/TR/html51/infrastructure.html#space-character).

You're confusing it with "skip White_Space characters", which is immediately after

> The step **skip White_Space characters** means that the user agent must collect a sequence of characters that are White_Space characters. In both cases, the collected characters are not used. [UNICODE]

**Comment by jdalton** [comment] 2015-01-09 21:05
> It would have been much more convenient and simpler overall if they could have just used one set of whitespace characters with the full unicode set.

<< Shakes fist at spec >>

Verified classLists get all wonky with other whitespaces:
![full wonky](https://cloud.githubusercontent.com/assets/4303/5687292/1dfc3514-9800-11e4-9b50-9a524fbadd9b.png)

**Comment by jdalton** [comment] 2015-01-09 21:14
For whitespace it may be easier to standardize on what `amp-trim` handles that way whitespace handling is consistent throughout. So while the spec may be more restricted on space-separated tokens `amp` could take the stance that for consistency and simplicity it standardizes on a single set of what it considers whitespace.

**Comment by zzzzBov** [comment] 2015-01-09 21:30
> For whitespace it may be easier to standardize on what amp-trim handles that way whitespace handling is consistent throughout. So while the HTML spec may be more narrow on space-separated tokens amp could take the stance that for consistency and simplicity it opts to follow a single set of whitespace.

@jdalton, i understand where you're coming from, but be careful with that line of thinking. [non-breaking spaces][1] are a form of white space, but in many cases should not be treated the same as other white space.

This is a case where there's a known spec, and it's clear, so I would encourage following standard behavior (at the cost of a few bytes of code and minutes of discussion) rather than diverging from the spec and suffering the consequences.

[1]: http://en.wikipedia.org/wiki/Non-breaking_space

**Comment by jdalton** [comment] 2015-01-09 21:43
> and suffering the consequences

In the case of `amp-trim` it covers more whitespace so worse case some edge whitespace is not allowed but I imagine that's hardly common and seems like a reasonable tradeoff for simplicity & consistency.

**Comment by jdalton** [comment] 2015-01-09 22:07
Also to the whole erroring thing. That's against the grain on most of Underscore and Amp by proxy. The existing convention to is handle things gracefully and avoid throwing when possible.

**Comment by Anachron** [comment] 2015-01-12 17:27
Don't forget there are libraries like Semantic UI which use multiple class names on the same element.

**Comment by Anachron** [comment] 2015-01-12 17:28
I mean multiple times the same clas, like: 'left aligned left icon ui menu'.

**Comment by HenrikJoreteg** [comment] 2015-01-12 17:29
@Anachron you mean repeating class names?

**Comment by Anachron** [comment] 2015-01-12 17:41
Yup. If you filter duplicate classes, you will make it impossible to use UI Frameworks like SemanticUI.

**Comment by HenrikJoreteg** [comment] 2015-01-12 17:47
@Anachron Well, we already are. I'm not wanting to support that, to be honest. I'd rather make it smart enough to filter out dupes to avoid touching the DOM unless actually needed.

Also, that's what `classList` already does: https://developer.mozilla.org/en-US/docs/Web/API/Element.classList

**Comment by HenrikJoreteg** [comment] 2015-01-12 17:59
@Anachron from a quick glance at Semantic UI i don't see anything that requires support for repeating classes on the same element, care to point me in the right direction? have a link or something?

**Comment by Anachron** [comment] 2015-01-12 18:04
Sure, one of the examples is here:
https://github.com/Semantic-Org/Semantic-UI/issues/1526

**Comment by zzzzBov** [comment] 2015-01-12 18:42
> Don't forget there are libraries like Semantic UI which use multiple class names on the same element.

@Anachron This appears to be a completely separate issue, and should be addressed by opening a new ticket.

That said, it is foolish for any developer to rely on class order or duplication of classes being preserved. Such frameworks, no matter how well designed they appear, are best avoided in favor of maintainable standards-compliant solutions.

If you *must* break from the standards, it's better to implement a custom, framework-specific method for handling such cases.

**Comment by HenrikJoreteg** [comment] 2015-01-12 18:57
I've been contemplating this for a bit. Nowhere is it stated or implied that adding space-separated classes is possible, or encouraged, or will work. To me, this doesn't feel like something we need to handle in code.

I'm quite tempted to just call this a `nofix` and move on. Perhaps we just update the docs to say that this isn't supported?

**Comment by zzzzBov** [comment] 2015-01-12 19:36
> I'm quite tempted to just call this a `nofix` and move on. Perhaps we just update the docs to say that this isn't supported?

I really wasn't expecting that one. Sounds a lot like burying your head in the sand and pretending the issue will go away by wishful thinking. The code is trivial to write, and the performance is negligibly different.

But hey, if it's easier to just leave the bugs in, it's your project so feel free. I'll just make sure to spend my time improving a different one.

**Comment by jlukic** [comment] 2015-01-12 21:11
I can confirm that SUI uses "word order dependency" https://github.com/Semantic-Org/Semantic-UI/issues/396

> it is foolish for any developer to rely on class order or duplication of classes being preserved. Such  frameworks, no matter how well designed they appear, are best avoided in favor of maintainable standards-compliant solutions.

I think an argument that "the standard says to do X or Y" is an appeal to authority and not by its own right an argument for validity. All language changes come from changes in adoption, which requires someone to decide to deviate from orthodoxy. The usefulness of this deviation is then tested against a larger group of "language speakers", which accept or rejects the change with the voting power of usage or adoption. I'd recommend checking [this essay from the forward of Modern American Usage](http://www.oxforddictionaries.com/us/external/files/Garner_s_American_The_Ongoing_Struggles_of_Garlic-Hangers.pdf?version=2014-10-15-1630) for some fun anecdotes on how this "prescriptivist/descriptivist dilemma" can create funny circumstances in the context of language usage. 

With regards to the conversation at hand. I admit, word order dependency with class names is not a very widely adopted technique. I apologize for the annoyance I've added with by creating a framework that uses meaningful whitespace with class names. 

I don't have any magic bullet ideas on a best way forward. I'm partial to the idea of dupe removal being an 'optional feature' of utilities that add/remove class names, with either different methods for each, or a separate optional parameter for disabling dupe removal. Of course as mentioned earlier, sadly the native APIs [don't support this]([mdn article](https://developer.mozilla.org/en-US/docs/Web/API/Element.classList), but that doesn't mean us in userland can't work around this.

**Comment by HenrikJoreteg** [comment] 2015-01-12 21:55
@zzzzBov tim, sorry if that sounded rude that was certainly not my intent. 

> Perhaps we just update the docs to say that this isn't supported?

I ended that with a question mark and didn't close this yet because I was floating that suggestion for feedback. I didn't mean to offend, my apologies.

I guess the thing I'm still wondering is why one would assume that this particular case would be handled, given that the docs say nothing of it? I personally wouldn't expect adding a space-separated string to work and i've always thought it a bit odd that jQuery's api does, but maybe i'm in the minority.

**Comment by HenrikJoreteg** [comment] 2015-01-12 21:56
I can certainly see the point that people would assume this to be the case if they're used to that type of behavior elsewhere.

**Comment by HenrikJoreteg** [comment] 2015-01-12 21:57
also, would we also handle the case where someone does this? 

`addClass(el, 'class1 class2', 'class3')` ?

**Comment by jdalton** [comment] 2015-01-12 21:59
Space separated string feels natural like like `el.className += ' foo bar'` and makes sense in the context of class names at least. Underscore handles juggling similar to this with its `flatten` internal helper to allow methods like `_.pick` to support individual arguments or arrays of arguments or a mix. This would be similar except splitting after flattening to an array of class names you then split them by whitespace.

**Comment by Anachron** [comment] 2015-01-12 22:19
I've been checking this: http://www.w3.org/TR/html401/struct/global.html#adef-class

Quote: `This attribute assigns a class name or set of class names to an element. Any number of elements may be assigned the same class name or names. Multiple class names must be separated by white space characters.`

I'd argue that they probably did not think of someone using the same class multiple times on the same element back then. However:

In the newest version I read this: http://www.w3.org/TR/2014/REC-html5-20141028/dom.html#classes
`3.2.5.7 The class attribute

Every HTML element may have a class attribute specified.

The attribute, if specified, must have a value that is a set of space-separated tokens representing the various classes that the element belongs to.

The classes that an HTML element has assigned to it consists of all the classes returned when the value of the class attribute is split on spaces. (Duplicates are ignored.)`

So you could probably say that they have been taking care of that now. Not good for Semantic UI :-1: 

@jlukic @HenrikJoreteg

**Comment by zzzzBov** [comment] 2015-01-12 22:21
> I think an argument that "the standard says to do X or Y" acts as an appeal to authority and not necessarily an argument for validity. Just like an argument over the morality of the death penalty would be stopped short if we just said if we relied on a de jure argumnet like, "Well its current (legal/illegal) in my country".

@jlukic I feel like your analogy between APIs and laws is being applied inconsistently. I'm not arguing that "whatever the API says is inherently correct". It would be more accurate to compare following a standardized API with obeying the law. You might disagree with the law, and there might be problems with the law. The generally accepted behavior is to follow the law, and to communicate any issues to lawmakers so that they can be resolved. The equivalent as far as a standardized API is concerned would be to raise the issue with the standards body.

If you'd like to engage in "civil disobedience" as it may be, that is your choice.

> With regards to the conversation at hand. I admit, word order dependency with class names is not a very widely adopted technique. I apologize for the annoyance I've added with by creating a framework that uses meaningful whitespace with class names.

"meaningful whitespace" doesn't annoy me, but it seems foolish when [the specification clearly says whitespace (well, a subset at least) should be skipped][1]. I'd encourage you to join the mailing lists and voice your opinion on semantic whitespace if you think the specification is wrong in this regard.

> I don't have any magic bullet ideas on a best way forward. I'm partial to the idea of dupe removal being an 'optional feature' of utilities that add/remove class names, with either different methods for each or a separate optional parameter or setting for disabling duplicate removal.

Rather than trying to hijack classes, I'd recommend using a different attribute altogether. You can create your own `[data-*]` attribute, or use a namespaced attribute, or if you're like angular, make up your own and pretend that they're valid (I'm looking at you `[ng-*]` attributes). That way, there's no risk of your list order or whitespace being messed up by an api that was never meant to handle those requirements.

More importantly, the right thing to do is come up with an API that is designed with those additional requirements in mind.

`addClass`, `hasClass`, and `removeClass` probably aren't even the right methods for an implementation that requires ordering, whitespace preservation, and name duplication.

You'd probably want `appendClass`, `prependClass`, `swapClass`, `hasClassGroup`, `removeClassAt`, `addClassTo`, and any other variation that could actually do the job needed.

[1]: http://www.w3.org/TR/html51/single-page.html#set-of-space-separated-tokens

**Comment by zzzzBov** [comment] 2015-01-12 22:41
<sub>pseudo-code used for brevity</sub>

> also, would we also handle the case where someone does this?
> 
> `addClass(el, 'class1 class2', 'class3')`?

If I saw a line of code that read as

    addClass(<div>, 'class1 class2', 'class3')

I would expect it to result in

    <div class="class1 class2 class3">

Likewise, I'd expect

    addClass(<div>, ['class1', 'class2'], 'class3 class4')

to result in

    <div class="class1 class2 class3 class4">

It seems like a simple application of

1. flatten (squish any array input into a single collection)
1. map (split on whitespace)
1. flatten (again)
1. filter (empties)
1. iterate (add or remove classes as needed)

Steps 2 and 3 can be condensed if you use something akin to linq's `SelectMany`.

**Comment by jlukic** [comment] 2015-01-13 03:14
@zzzzBov The analogy with law was a bit flaccid. 

To understand my perspective when language authoring I recommend reading [this essay](http://wilson.med.harvard.edu/nb204/AuthorityAndAmericanUsage.pdf) that discusses the current in fighting over language. For a perspective on my understanding of classical inheritance, a certain [theory of forms](http://www.anselm.edu/homepage/dbanach/platform.htm). For the importance of context and structure in language [Wittgenstein wrote best](http://postmoderntherapies.com/word.html) and finally on creating formal systems to deconstruct language [Montague](http://plato.stanford.edu/entries/montague-semantics/) and his successors. I know these aren't normally argued positions in C.S. so this is why I'm taking the indulgence of sharing. 

In my personal opinion CS "classes", words, and (platonic) forms are all the same thing. With respects to languages, constructed or otherwise, passing around jumbled up sentences seems like an awfully regressive way of doing things. It is regretfully the *standard of the era*, but hopefully we can fight to change that.

I don't think this line of argument will have much bearing on the current state of technologies for 20x0 web, but perhaps for posterity, and for influencing the quite remarkable minds that are in this conversation, it's worth making them now. I think once we all get our glorious 60FPS of 2d text and video rendering to screens at under 1 second we're definitely going to find new things to argue about, and I personally don't think that day is too far off.

**Comment by HenrikJoreteg** [comment] 2015-01-13 05:48
ok, so after some additional chat conversations I think it makes sense to support space separated, but supporting mixed approaches doesn't feel right and is noted in docs. I don't want to encourage or enable people to write code that inconsistent.

If there's really a scenario where a dev is building some crazy class list from strings and arrays there's nothing stopping them from flattening the list first. It seems unlikely and unreasonable for them to expect that kind of thing to just work.

Also, with regard to `hasClass` we opted in pre-release conversations to only have it support a single class string this is because it disambiguates whether it's an `and` or and `or` and also whether order is significant. It's also consistent with `toggle-class`. 

It's also easy enough to do: `hasClass(el, 'foo') || hasClass(el, 'bar')` if you need to.

Thanks everyone for your input, I'm closing this in lieu of that PR.

**Closed by HenrikJoreteg** 2015-01-13 05:48 UTC
Labels: question
